// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpbT7hrzKE_gz25UaNAG_Xkyi2rRNWGGg',
    appId: '1:217995668835:web:d44dd55eb8e6fa598af756',
    messagingSenderId: '217995668835',
    projectId: 'agrosmart-teste-daniel-araujo',
    authDomain: 'agrosmart-teste-daniel-araujo.firebaseapp.com',
    storageBucket: 'agrosmart-teste-daniel-araujo.appspot.com',
    measurementId: 'G-DFJC4KTEKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwvQPh-MZNCZLYk3NWkEgcoz7dPmmVjY',
    appId: '1:217995668835:android:3131b64c9bca9d2f8af756',
    messagingSenderId: '217995668835',
    projectId: 'agrosmart-teste-daniel-araujo',
    storageBucket: 'agrosmart-teste-daniel-araujo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdPdIwwzUJj_xrafYECuT-VuGA8nJxkcI',
    appId: '1:217995668835:ios:2789738703d406ad8af756',
    messagingSenderId: '217995668835',
    projectId: 'agrosmart-teste-daniel-araujo',
    storageBucket: 'agrosmart-teste-daniel-araujo.appspot.com',
    iosClientId: '217995668835-o6tkfrjaddvmr0m4oet6sgmv1g2t14s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrosmartListaProdutosTesteDanielAraujo',
  );
}
